import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const source = resolve("site"), output = resolve("dist");
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await cp(source, output, { recursive: true, filter: (item) => !item.endsWith("config.example.js") });
const projectUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";
await writeFile(resolve(output, "config.js"), `window.RANKING_CONFIG = ${JSON.stringify({ SUPABASE_URL: projectUrl, SUPABASE_ANON_KEY: anonKey })};\n`);
if (!projectUrl || !anonKey) console.warn("Supabase variables are missing. The published interface will show a configuration message.");
